import { contextBridge, ipcRenderer } from 'electron';
import type { BackendState, ResearchTrailBridge, RunStreamUpdate } from '../bridge';

const bridge: ResearchTrailBridge = {
  outcomeOpinions: () => ipcRenderer.invoke('outcomes:opinions'),
  captureOutcome: input => ipcRenderer.invoke('outcomes:capture',input),
  outcomeOpinion: id => ipcRenderer.invoke('outcomes:opinion',id),
  evaluateOutcome: (id,requestId) => ipcRenderer.invoke('outcomes:evaluate',id,requestId),
  outcomePolicies: () => ipcRenderer.invoke('outcomes:policies'),
  changeOutcomePolicy: input => ipcRenderer.invoke('outcomes:policy-change',input),
  outcomePerformance: input => ipcRenderer.invoke('outcomes:performance',input),
  outcomeSnapshot: id => ipcRenderer.invoke('outcomes:snapshot',id),
  evaluationCases: () => ipcRenderer.invoke('evaluation:evaluationCases'),
  evaluationExperiments: () => ipcRenderer.invoke('evaluation:evaluationExperiments'),
  createExperiment: (input) => ipcRenderer.invoke('evaluation:createExperiment',input),
  evaluationExperiment: (id,baselineId) => ipcRenderer.invoke('evaluation:evaluationExperiment',id,baselineId),
  startExperiment: (id) => ipcRenderer.invoke('evaluation:startExperiment',id),
  cancelExperiment: (id) => ipcRenderer.invoke('evaluation:cancelExperiment',id),
  evaluationBaselines: () => ipcRenderer.invoke('evaluation:evaluationBaselines'),
  saveEvaluationBaseline: (input) => ipcRenderer.invoke('evaluation:saveEvaluationBaseline',input),
  evaluationFeedback: (id) => ipcRenderer.invoke('evaluation:evaluationFeedback',id),
  addEvaluationFeedback: (id,input) => ipcRenderer.invoke('evaluation:addEvaluationFeedback',id,input),
  tracingConfigurations: () => ipcRenderer.invoke('evaluation:tracingConfigurations'),
  saveTracingConfiguration: (provider,input) => ipcRenderer.invoke('evaluation:saveTracingConfiguration',provider,input),
  saveTracingCredential: (provider,input) => ipcRenderer.invoke('evaluation:saveTracingCredential',provider,input),
  deleteTracingCredential: (provider) => ipcRenderer.invoke('evaluation:deleteTracingCredential',provider),
  probeTracing: (provider) => ipcRenderer.invoke('evaluation:probeTracing',provider),
  previewEvaluationTrace: (provider,id) => ipcRenderer.invoke('evaluation:previewEvaluationTrace',provider,id),
  uploadEvaluationTrace: (provider,id,input) => ipcRenderer.invoke('evaluation:uploadEvaluationTrace',provider,id,input),
  evaluationTraceDeliveries: () => ipcRenderer.invoke('evaluation:evaluationTraceDeliveries'),
  today: timezone => ipcRenderer.invoke('today:view',timezone),
  monitoringRules: () => ipcRenderer.invoke('monitoring:rules'),
  createMonitoringRule: input => ipcRenderer.invoke('monitoring:create',input),
  toggleMonitoringRule: (id,enabled) => ipcRenderer.invoke('monitoring:toggle',id,enabled),
  monitoringRuns: () => ipcRenderer.invoke('monitoring:runs'),
  monitoringResearch: (id,symbol) => ipcRenderer.invoke('monitoring:research',id,symbol),
  calendarSources: input => ipcRenderer.invoke('calendar:sources',input),
  refreshCalendar: input => ipcRenderer.invoke('calendar:refresh',input),
  calendarHistory: () => ipcRenderer.invoke('calendar:history'),
  calendarView: (id,timezone) => ipcRenderer.invoke('calendar:view',id,timezone),
  calendarOriginal: (id,readId) => ipcRenderer.invoke('calendar:original',id,readId),
  screeningTasks: context => ipcRenderer.invoke('screening:tasks',context),
  startScreening: input => ipcRenderer.invoke('screening:start',input),
  screeningRuns: () => ipcRenderer.invoke('screening:list'),
  screeningRun: id => ipcRenderer.invoke('screening:get',id),
  cancelScreening: id => ipcRenderer.invoke('screening:cancel',id),
  screeningEvidence: (id,readId) => ipcRenderer.invoke('screening:evidence',id,readId),
  thesisList: () => ipcRenderer.invoke('theses:list'),
  createThesis: input => ipcRenderer.invoke('theses:create', input),
  thesis: id => ipcRenderer.invoke('theses:get', id),
  thesisVersion: (id, version) => ipcRenderer.invoke('theses:version', id, version),
  editThesis: (id, input) => ipcRenderer.invoke('theses:edit', id, input),
  evaluateThesis: (id, input) => ipcRenderer.invoke('theses:evaluate', id, input),
  judgeThesis: (id, input) => ipcRenderer.invoke('theses:judge', id, input),
  thesisReview: (id, reviewId) => ipcRenderer.invoke('theses:review', id, reviewId),
  reportList: runId => ipcRenderer.invoke('reports:list', runId),
  generateReport: (runId, mode, requestId) => ipcRenderer.invoke('reports:generate', runId, mode, requestId),
  report: id => ipcRenderer.invoke('reports:get', id),
  cancelReport: id => ipcRenderer.invoke('reports:cancel', id),
  reportEvidence: (id, evidenceId) => ipcRenderer.invoke('reports:evidence', id, evidenceId),
  exportReport: id => ipcRenderer.invoke('reports:export', id),
  reportDiff: (beforeId, afterId) => ipcRenderer.invoke('reports:diff', beforeId, afterId),
  researchStrategies: () => ipcRenderer.invoke('research:strategies'),
  researchPlan: input => ipcRenderer.invoke('research:plan', input),
  researchRuns: () => ipcRenderer.invoke('research:list'),
  startResearch: input => ipcRenderer.invoke('research:start', input),
  researchRun: id => ipcRenderer.invoke('research:get', id),
  cancelResearch: id => ipcRenderer.invoke('research:cancel', id),
  researchData: (id, capability) => ipcRenderer.invoke('research:data', id, capability),
  researchCheckpoint: id => ipcRenderer.invoke('research:checkpoint', id),
  resumeResearch: (id, requestId) => ipcRenderer.invoke('research:resume', id, requestId),
  restartResearch: (id, requestId) => ipcRenderer.invoke('research:restart', id, requestId),
  abandonResearch: (id, requestId) => ipcRenderer.invoke('research:abandon', id, requestId),
  capabilities: context => ipcRenderer.invoke('capabilities:list', context),
  skills: context => ipcRenderer.invoke('skills:list', context),
  setSkillEnabled: (id, enabled, context) => ipcRenderer.invoke('skills:enabled', id, enabled, context),
  readSkillResource: (id, path, context) => ipcRenderer.invoke('skills:resource', id, path, context),
  portfolioList: () => ipcRenderer.invoke('portfolios:list'),
  portfolioRisk: input => ipcRenderer.invoke('analytics:risk', input),
  compareStocks: input => ipcRenderer.invoke('analytics:compare', input),
  createPortfolio: input => ipcRenderer.invoke('portfolios:create', input),
  portfolioView: id => ipcRenderer.invoke('portfolios:view', id),
  previewPortfolio: (id, csv) => ipcRenderer.invoke('portfolios:preview', id, csv),
  confirmPortfolio: (id, draft) => ipcRenderer.invoke('portfolios:confirm', id, draft),
  undoPortfolio: (id, batch) => ipcRenderer.invoke('portfolios:undo', id, batch),
  refreshPortfolio: id => ipcRenderer.invoke('portfolios:refresh', id),
  workspaceState: () => ipcRenderer.invoke('workspace:state'),
  addWatch: symbol => ipcRenderer.invoke('workspace:add', symbol),
  removeWatch: symbol => ipcRenderer.invoke('workspace:remove', symbol),
  selectSecurity: symbol => ipcRenderer.invoke('workspace:select', symbol),
  securityPage: query => ipcRenderer.invoke('workspace:page', query),
  openNewsSource: url => ipcRenderer.invoke('workspace:news-link', url),
  providerProfiles: () => ipcRenderer.invoke('providers:profiles'),
  saveProvider: (provider, input) => ipcRenderer.invoke('providers:save', provider, input),
  deleteProvider: (provider) => ipcRenderer.invoke('providers:delete', provider),
  saveProviderCredential: (provider, input) => ipcRenderer.invoke('providers:credential-save', provider, input),
  deleteProviderCredential: (provider) => ipcRenderer.invoke('providers:credential-delete', provider),
  providerCapabilities: () => ipcRenderer.invoke('providers:capabilities'),
  queryProvider: (provider, input) => ipcRenderer.invoke('providers:query', provider, input),
  connections: () => ipcRenderer.invoke('settings:connections'),
  saveConnection: (kind, input) => ipcRenderer.invoke('settings:save', kind, input),
  deleteConnection: (kind) => ipcRenderer.invoke('settings:delete', kind),
  saveCredential: (kind, secret) => ipcRenderer.invoke('settings:credential-save', kind, secret),
  deleteCredential: (kind) => ipcRenderer.invoke('settings:credential-delete', kind),
  testConnection: (kind) => ipcRenderer.invoke('settings:test', kind),
  profile: () => ipcRenderer.invoke('settings:profile'),
  saveProfile: (input) => ipcRenderer.invoke('settings:profile-save', input),
  deleteProfile: () => ipcRenderer.invoke('settings:profile-delete'),
  diagnostics: () => ipcRenderer.invoke('settings:diagnostics'),
  exportDiagnostics: () => ipcRenderer.invoke('settings:diagnostics-export'),
  status: () => ipcRenderer.invoke('backend:status'),
  checkHealth: () => ipcRenderer.invoke('backend:check'),
  retryBackend: () => ipcRenderer.invoke('backend:retry'),
  marketSymbols: () => ipcRenderer.invoke('market:symbols'),
  marketSnapshot: (symbol) => ipcRenderer.invoke('market:snapshot', symbol),
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  createSession: (title) => ipcRenderer.invoke('sessions:create', title),
  getSession: (id) => ipcRenderer.invoke('sessions:get', id),
  deleteSession: (id) => ipcRenderer.invoke('sessions:delete', id),
  sessionMessages: (id) => ipcRenderer.invoke('sessions:messages', id),
  sessionRuns: (id) => ipcRenderer.invoke('sessions:runs', id),
  sessionSnapshot: (id) => ipcRenderer.invoke('sessions:snapshot', id),
  startRun: (id, input) => ipcRenderer.invoke('runs:start', id, input),
  startAgentRun: (id, input, scenario = 'normal', kind = 'fake_agent') => ipcRenderer.invoke('runs:agent', id, input, scenario, kind),
  cancelRun: (id, runId) => ipcRenderer.invoke('runs:cancel', id, runId),
  getRun: (id, runId) => ipcRenderer.invoke('runs:get', id, runId),
  runEvents: (id, runId, after = 0) => ipcRenderer.invoke('runs:events', id, runId, after),
  subscribeRun(id, runId, after, callback) {
    const key = crypto.randomUUID();
    const listener = (_event: unknown, receivedKey: string, value: RunStreamUpdate) => { if (receivedKey === key) callback(value); };
    ipcRenderer.on('runs:changed', listener);
    ipcRenderer.send('runs:subscribe', key, id, runId, after);
    let closed = false;
    return () => {
      if (closed) return;
      closed = true;
      ipcRenderer.removeListener('runs:changed', listener);
      ipcRenderer.send('runs:unsubscribe', key);
    };
  },
  onStatus(callback) {
    const listener = (_event: unknown, state: BackendState) => callback(state);
    ipcRenderer.on('backend:changed', listener);
    return () => ipcRenderer.removeListener('backend:changed', listener);
  },
};
contextBridge.exposeInMainWorld('researchTrail', bridge);
