import type { MarketResult, MarketSymbol } from './market-types';
import type { SessionDTO, MessageDTO, RunDTO, StreamEvent, SessionSnapshot } from './conversation-types';
export type RunStreamUpdate = { kind: 'event'; event: StreamEvent } |
  { kind: 'connection'; phase: 'connecting' | 'connected' | 'reconnecting' | 'closed' | 'failed'; detail: string };
export type BackendPhase = 'idle' | 'starting' | 'healthy' | 'failed' | 'stopping';
export interface BackendState {
  phase: BackendPhase;
  detail: string;
  checkedAt?: string;
  pythonVersion?: string;
}
export interface ResearchTrailBridge {
  today(timezone: string): Promise<import('./monitoring-types').TodayView>;
  monitoringRules(): Promise<import('./monitoring-types').RuleView[]>;
  createMonitoringRule(input: import('./monitoring-types').RuleInput): Promise<import('./monitoring-types').RuleView>;
  toggleMonitoringRule(id: string, enabled: boolean): Promise<import('./monitoring-types').RuleView>;
  monitoringRuns(): Promise<import('./monitoring-types').MonitorRun[]>;
  monitoringResearch(id: string, symbol: string): Promise<import('./monitoring-types').MonitorResearchAction>;
  calendarSources(input: import('./calendar-types').CalendarSelection): Promise<import('./calendar-types').CalendarSource[]>;
  refreshCalendar(input: import('./calendar-types').CalendarRefresh): Promise<import('./calendar-types').CalendarPage>;
  calendarHistory(): Promise<import('./calendar-types').CalendarSummary[]>;
  calendarView(id: string,timezone: string): Promise<import('./calendar-types').CalendarPage>;
  calendarOriginal(id: string,readId: string): Promise<import('./calendar-types').CalendarOriginal>;
  screeningTasks(context: import('./screening-types').ScreeningContext): Promise<import('./screening-types').ScreeningTask[]>;
  startScreening(input: import('./screening-types').ScreeningInput): Promise<import('./screening-types').ScreeningRun>;
  screeningRuns(): Promise<import('./screening-types').ScreeningSummary[]>;
  screeningRun(id: string): Promise<import('./screening-types').ScreeningRun>;
  cancelScreening(id: string): Promise<import('./screening-types').ScreeningRun>;
  screeningEvidence(id: string, readId: string): Promise<import('./screening-types').ScreeningEvidence>;
  thesisList(): Promise<import('./thesis-types').ThesisSummary[]>;
  createThesis(input: import('./thesis-types').ThesisCreate): Promise<import('./thesis-types').ThesisView>;
  thesis(id: string): Promise<import('./thesis-types').ThesisView>;
  thesisVersion(id: string, version: number): Promise<import('./thesis-types').ThesisVersion>;
  editThesis(id: string, input: import('./thesis-types').ThesisEdit): Promise<import('./thesis-types').ThesisView>;
  evaluateThesis(id: string, input: import('./thesis-types').ThesisEvaluate): Promise<import('./thesis-types').ThesisReview>;
  judgeThesis(id: string, input: import('./thesis-types').ThesisJudge): Promise<import('./thesis-types').ThesisView>;
  thesisReview(id: string, reviewId: string): Promise<import('./thesis-types').ThesisReview>;
  reportList(runId?: string): Promise<import('./report-types').ReportSummary[]>;
  generateReport(runId: string, mode: 'fixed' | 'real', requestId?: string): Promise<import('./report-types').ReportJob>;
  report(id: string): Promise<import('./report-types').ReportJob>;
  cancelReport(id: string): Promise<import('./report-types').ReportJob>;
  reportEvidence(id: string, evidenceId: string): Promise<import('./report-types').ReportOriginal>;
  exportReport(id: string): Promise<boolean>;
  reportDiff(beforeId: string, afterId: string): Promise<import('./report-types').ReportDiff>;
  researchStrategies(): Promise<import('./research-types').ResearchStrategy[]>;
  researchPlan(input: import('./research-types').ResearchInput): Promise<import('./research-types').ResearchPlan>;
  researchRuns(): Promise<import('./research-types').ResearchSummary[]>;
  startResearch(input: import('./research-types').ResearchInput): Promise<import('./research-types').ResearchRun>;
  researchRun(id: string): Promise<import('./research-types').ResearchRun>;
  cancelResearch(id: string): Promise<import('./research-types').ResearchRun>;
  researchData(id: string, capability: string): Promise<import('./research-types').ResearchData>;
  researchCheckpoint(id: string): Promise<import('./research-types').RecoveryView>;
  resumeResearch(id: string, requestId: string): Promise<import('./research-types').ResearchRun>;
  restartResearch(id: string, requestId: string): Promise<import('./research-types').ResearchRun>;
  abandonResearch(id: string, requestId: string): Promise<import('./research-types').ResearchRun>;
  capabilities(context: import('./skill-types').SkillContext): Promise<import('./skill-types').CapabilityState[]>;
  skills(context: import('./skill-types').SkillContext): Promise<import('./skill-types').SkillView[]>;
  setSkillEnabled(id: string, enabled: boolean, context: import('./skill-types').SkillContext): Promise<import('./skill-types').SkillView>;
  readSkillResource(id: string, path: string, context: import('./skill-types').SkillContext): Promise<import('./skill-types').SkillResource>;
  portfolioList(): Promise<import('./portfolio-types').PortfolioInfo[]>;
  portfolioRisk(input: import('./analytics-types').RiskQuery): Promise<import('./analytics-types').RiskReport>;
  compareStocks(input: import('./analytics-types').CompareQuery): Promise<import('./analytics-types').Comparison>;
  createPortfolio(input: import('./portfolio-types').PortfolioCreate): Promise<import('./portfolio-types').PortfolioView>;
  portfolioView(id: string): Promise<import('./portfolio-types').PortfolioView>;
  previewPortfolio(id: string, csv: string): Promise<import('./portfolio-types').ImportPreview>;
  confirmPortfolio(id: string, draft: string): Promise<import('./portfolio-types').PortfolioView>;
  undoPortfolio(id: string, batch: string): Promise<import('./portfolio-types').PortfolioView>;
  refreshPortfolio(id: string): Promise<import('./portfolio-types').PortfolioView>;
  workspaceState(): Promise<import('./workspace-types').WorkspaceState>;
  addWatch(symbol: string): Promise<import('./workspace-types').WorkspaceState>;
  removeWatch(symbol: string): Promise<import('./workspace-types').WorkspaceState>;
  selectSecurity(symbol: string): Promise<import('./workspace-types').WorkspaceState>;
  securityPage(query: import('./workspace-types').SecurityQuery): Promise<import('./workspace-types').SecurityPage>;
  openNewsSource(url: string): Promise<void>;
  providerProfiles(): Promise<import('./provider-types').ProviderProfile[]>;
  saveProvider(provider: import('./provider-types').ProviderId, input: import('./provider-types').ProviderConfiguration): Promise<import('./provider-types').ProviderProfile>;
  deleteProvider(provider: import('./provider-types').ProviderId): Promise<import('./provider-types').ProviderProfile>;
  saveProviderCredential(provider: import('./provider-types').ProviderId, input: import('./provider-types').ProviderCredentials): Promise<import('./provider-types').ProviderProfile>;
  deleteProviderCredential(provider: import('./provider-types').ProviderId): Promise<import('./provider-types').ProviderProfile>;
  providerCapabilities(): Promise<import('./provider-types').CapabilityView[]>;
  queryProvider(provider: import('./provider-types').ProviderId, input: import('./provider-types').ReadQuery): Promise<import('./provider-types').ProviderResult>;
  connections(): Promise<import('./settings-types').ConnectionView[]>;
  saveConnection(kind: import('./settings-types').ConnectionKind, input: import('./settings-types').ConnectionInput): Promise<import('./settings-types').ConnectionView>;
  deleteConnection(kind: import('./settings-types').ConnectionKind): Promise<import('./settings-types').ConnectionView>;
  saveCredential(kind: import('./settings-types').ConnectionKind, secret: string): Promise<import('./settings-types').ConnectionView>;
  deleteCredential(kind: import('./settings-types').ConnectionKind): Promise<import('./settings-types').ConnectionView>;
  testConnection(kind: import('./settings-types').ConnectionKind): Promise<import('./settings-types').ConnectionView>;
  profile(): Promise<import('./settings-types').Profile>;
  saveProfile(input: import('./settings-types').Profile): Promise<import('./settings-types').Profile>;
  deleteProfile(): Promise<import('./settings-types').Profile>;
  diagnostics(): Promise<import('./settings-types').Diagnostics>;
  exportDiagnostics(): Promise<boolean>;
  status(): Promise<BackendState>;
  checkHealth(): Promise<BackendState>;
  retryBackend(): Promise<BackendState>;
  marketSymbols(): Promise<MarketSymbol[]>;
  marketSnapshot(symbol: string): Promise<MarketResult>;
  listSessions(): Promise<SessionDTO[]>;
  createSession(title: string): Promise<SessionDTO>;
  getSession(sessionId: string): Promise<SessionDTO>;
  deleteSession(sessionId: string): Promise<void>;
  sessionMessages(sessionId: string): Promise<MessageDTO[]>;
  sessionRuns(sessionId: string): Promise<RunDTO[]>;
  sessionSnapshot(sessionId: string): Promise<SessionSnapshot>;
  startRun(sessionId: string, input: string): Promise<RunDTO>;
  startAgentRun(sessionId: string, input: string, scenario?: 'normal' | 'delayed' | 'timeout', kind?: 'fake_agent' | 'openai_agent'): Promise<RunDTO>;
  cancelRun(sessionId: string, runId: string): Promise<RunDTO>;
  getRun(sessionId: string, runId: string): Promise<RunDTO>;
  runEvents(sessionId: string, runId: string, afterSequence?: number): Promise<StreamEvent[]>;
  subscribeRun(sessionId: string, runId: string, afterSequence: number, callback: (update: RunStreamUpdate) => void): () => void;
  onStatus(callback: (state: BackendState) => void): () => void;
}
